# Generated by Django 4.2.2 on 2023-07-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
